blank_issues_enabled: false
contact_links:
  - name: Auth0 Community
    url: https://community.auth0.com/c/sdks/5
    about: Discuss this SDK in the Auth0 Community forums
  - name: Terraform Provider Documentation
    url: https://registry.terraform.io/providers/auth0/auth0/latest/docs
    about: Read the documentation for this Terraform provider
