name: Sweep

on: [workflow_dispatch]

jobs:
  sweep:
    name: Sweep
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.1
      id: go
    - name: Set up Git cookies
      run: bash scripts/gogetcookie.sh
    - name: Sweep
      run: make sweep
      env:
        AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}